### ISSUE TITLE
with minibatch disabled or tiny batch size of 5, we get 20-30 extra rows, or NullPointer crash

### ISSUE THREAD

**Issue by nparrish42** [fentik/flink#10]
testing 2e13861.
this query has proven rather productive in turning up bugs...
```
(venv) [nathan@devbox /opt/dataflo/python]$ cat stream/flink/test/sql/next_10_selling_products_by_category_no_rownum.sql
WITH product_sales_totals AS (
    SELECT  product_name,
            category,
            SUM(CAST(quantity AS INT) * price) AS total_sales
        FROM order_items
        GROUP BY product_name, category
)
SELECT category, product_name
FROM (
    SELECT  product_name,
            category,
            row_number() OVER (PARTITION BY category
                            ORDER BY total_sales DESC) AS row_num
    FROM product_sales_totals)
    WHERE row_num BETWEEN 11 AND 20;
```

when running with minibatch disabled (`SET table.exec.mini-batch.enabled='false';`) or a tiny batch size set (`SET table.exec.mini-batch.size='5';`), we are seeing an extra 20-30 rows being returned (vs. postgres), or, more occasionally, a null pointer crash, but for which I have been unable to turn up a stack trace (only the rpc/rest stacktraces around handling the failure).  

note that the variant of this query where the row number is included in the output works just fine.

example of extra output:
```
__main__.ResultMismatchError: dataflo 34 unique rows:
Automotive, Granite Intelligent Chips
Beauty, Cotton Awesome Fish
Books, Wooden Refined Pants
Clothing, Plastic Small Shirt
Computers, Concrete Small Tuna
Electronics, Concrete Unbranded Bacon
Games, Metal Gorgeous Sausages
Games, Soft Small Car
Games, Wooden Used Chips
Garden, Soft Handmade Ball
Grocery, Cotton Gently Used Keyboard
Grocery, Frozen Sleek Chicken
Health, Concrete Gorgeous Pizza
Home, Concrete Tasty Pants
Home, Fresh Fantastic Towels
Industrial, Metal Tasty Salad
Jewelery, Concrete Used Sausages
Jewelery, Frozen Generic Shirt
Jewelery, Steel Used Towels
Kids, Cotton Practical Pants
Kids, Soft Handmade Salad
Kids, Wooden Fantastic Gloves
Movies, Soft Small Table
Movies, Steel Awesome Ball
Music, Granite Small Hat
Shoes, Rubber Sleek Pizza
Sports, Cotton Gently Used Chair
Tools, Concrete Incredible Cheese
Tools, Concrete Small Shirt
Tools, Steel Gently Used Chips
Tools, Wooden For repair Chicken
Toys, Concrete Unbranded Tuna
Toys, Metal Refined Car
Toys, Wooden Incredible Sausages
postgres 220 results, dataflo 254
```

here's output from jobmanager supervisord log, but it's not helpful:
```
2022-09-11 01:05:13,922 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Rank[9] -> Calc[10] (1/2) (8395717cbdfeb9f09ead349c188e0852) switched from INITIALIZING to RUNNING.
2022-09-11 01:05:13,922 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Rank[9] -> Calc[10] (2/2) (e7fc588f4b47bab2d2abba000ee7d252) switched from INITIALIZING to RUNNING.
2022-09-11 01:05:13,922 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - ChangelogNormalize[4] -> Calc[5] (1/2) (35024d0e2885545773f0ed2808da3c5c) switched from INITIALIZING to RUNNING.
2022-09-11 01:05:13,942 INFO  org.apache.flink.streaming.api.operators.collect.CollectSinkOperatorCoordinator [] - Sink connection established
2022-09-11 01:05:13,999 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Rank[9] -> Calc[10] (1/2) (8395717cbdfeb9f09ead349c188e0852) switched from RUNNING to FAILED on localhost:37643-8fa29a @ localhost (dataPort=41999).
java.lang.NullPointerException: null
2022-09-11 01:05:14,000 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - Calculating tasks to restart to recover the failed task 852d82fa98a96db4a12085e753404e56_0.
2022-09-11 01:05:14,000 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - 9 tasks should be restarted to recover the failed task 852d82fa98a96db4a12085e753404e56_0. 
2022-09-11 01:05:14,000 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job regression_test_7c3a293b (adc13b03ab75bb22c1871361d7a9f9e8) switched from state RUNNING to FAILING.
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:301) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:291) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:282) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:739) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:78) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:443) ~[flink-dist-1.15.0.jar:1.15.0]
        at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:304) ~[flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83) ~[flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:302) ~[flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217) ~[flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78) ~[flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163) ~[flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.actor.Actor.aroundReceive(Actor.scala:537) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.actor.Actor.aroundReceive$(Actor.scala:535) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.actor.ActorCell.invoke(ActorCell.scala:548) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.dispatch.Mailbox.run(Mailbox.scala:231) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [flink-rpc-akka_f880e821-da2a-426b-9893-3d404e862d8c.jar:1.15.0]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.NullPointerException
```
I've looked through all logs in /opt/flink-1.15.0-rc1/log and can't find any crash that references flink-table-runtime-1.15.0.jar, only the error handling stuff similar to the above.

**Comment by sergeitsar** [comment]
Do you have the taskmanager log by any chance?

**Comment by sergeitsar** [comment]
suspect it's the same as issue #5
