### ISSUE TITLE
bad retraction with lag() with minibatch disabled -- -U specifying FALSE for NULL value

### ISSUE THREAD

**Issue by nparrish42** [fentik/flink#21]
test case is:
```
python -m stream.flink.test.flink_regression_test --postgres --audit --parallelism=2 --test-setting table.exec.mini-batch.enabled='false' stream/flink/test/sql/lag_gem_work_info_query.sql
```
failure is not 100%, but seems to happen more than half the time, and looks like:
```
[2022-12-06T17:34:10.198+0000 INFO flink_regression_test] +I ('4', '1600000000', '0', 'LongCorp', '<NULL>')
[2022-12-06T17:34:10.198+0000 INFO flink_regression_test] +I ('5', '1500000000', '<NULL>', 'LongCorp', '<NULL>')
[2022-12-06T17:34:10.198+0000 INFO flink_regression_test] -U ('4', '1600000000', '0', 'LongCorp', 'FALSE')
[2022-12-06T17:34:10.198+0000 INFO flink_regression_test] ^^^BAD RETRACTION^^^
[2022-12-06T17:34:10.198+0000 INFO flink_regression_test] +U ('4', '1600000000', '0', 'LongCorp', 'FALSE')
[2022-12-06T17:34:10.199+0000 INFO flink_regression_test] +I ('4', '1600000000', '<NULL>', 'LongCorp', '<NULL>')
[2022-12-06T17:34:10.199+0000 INFO flink_regression_test] -D ('5', '1500000000', '<NULL>', 'LongCorp', '<NULL>')
[2022-12-06T17:34:10.199+0000 INFO flink_regression_test] +I ('5', '1500000000', '0', 'LongCorp', '<NULL>')
[2022-12-06T17:34:10.200+0000 INFO flink_regression_test] -D ('4', '1600000000', '<NULL>', 'LongCorp', '<NULL>')
[2022-12-06T17:34:10.200+0000 INFO flink_regression_test] -U ('4', '1600000000', '0', 'LongCorp', 'FALSE')
[2022-12-06T17:34:10.200+0000 INFO flink_regression_test] +U ('4', '1600000000', '0', 'LongCorp', 'FALSE')
[2022-12-06T17:34:10.200+0000 INFO flink_regression_test] -U ('4', '1400000000', '1500000000', 'LongCorp', 'FALSE')
[2022-12-06T17:34:10.200+0000 INFO flink_regression_test] +U ('4', '1400000000', '1500000000', 'LongCorp', 'TRUE')
[2022-12-06T17:34:10.200+0000 INFO flink_regression_test] +I ('4', '1500000000', '1600000000', 'LongCorp', 'TRUE')
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/dataflo/python/stream/flink/test/flink_regression_test.py", line 398, in <module>
    main(args)
  File "/opt/dataflo/python/stream/flink/test/flink_regression_test.py", line 372, in main
    validate_against_postgres(
  File "/opt/dataflo/python/stream/flink/test/flink_regression_test.py", line 335, in validate_against_postgres
    compare_results(psql_res, dflo_res, "postgres", "dataflo")
  File "/opt/dataflo/python/stream/flink/test/compare_dbs.py", line 113, in compare_results
    raise ResultMismatchError(a, b, label_a, label_b)
stream.flink.test.compare_dbs.ResultMismatchError: dataflo 1 unique rows:
4, 1600000000, 0, LongCorp, FALSE
postgres 14 results, dataflo 15
```

**Comment by nparrish42** [comment]
I believe the history of this table on my devbox is crucial to reproducing this bug.  I initially created it with end_date NULL, before realizing that Gem uses 0 for end_date to indicate current employer.
thank goodness for .psql_history, here's a sequence of DDL and DML for postgres source which should trigger the bug (run in `psql product_db`:

```
CREATE TABLE work_info5 (
    id int,
    person_id int,
    start_date int,
    end_date int,
    company text,
    primary key (id)
);


-- LAG testcase data (based on Gem query which surfaced LAG requirement)
INSERT INTO work_info5 VALUES
    (1, 1, 1441080000, 1442080000, 'UniCorp'),
    (2, 1, 1442080000, 1443080000, 'UniCorp'), -- contiguous time at same company
    (3, 1, 1447080000, 1449080000, 'UniCorp'), -- gap but same company
    (4, 1, 1449080000, 1450080000, 'DuoCorp'), -- gap, different company
    (5, 2, 1441080000, 1442080000, 'UniCorp'),
    (6, 2, 1442090000, 1444100000, 'VeriCorp'),
    (7, 2, 1444080000, 1445080000, 'UniCorp'), -- yes, overlaps prior
    (8, 2, 1446080000, 1447080000, 'DuoCorp'), -- exact overlap with person 1
    (9, 2, 1447080000, 1448080000, 'DuoCorp'), -- contiguous same company
    (10, 3, 1500000000, 1600000000, 'VeriCorp'), -- only entry for this person
    (11, 4, 1200000000, 1300000000, NULL),
    (12, 4, 1300000000, 1400000000, NULL), -- consecutive but company is NULL
    (13, 4, 1400000000, 1500000000, 'LongCorp'),
    (14, 4, 1600000000, NULL, 'LongCorp'),
    (20, 5, 1500000000, NULL, 'LongCorp'); -- only entry for this person, no end date

update work_info5 set start_date=1500000000, end_date=1600000000 where id = 14;
insert into work_info5 (15, 4, 1600000000, NULL, 'LongCorp');
insert into work_info5 values (15, 4, 1600000000, NULL, 'LongCorp');

update work_info5 set end_date = 0 where end_date is null;
```

with `stream/flink/test/sql/lag_gem_work_info_query5.sql` as
```
select
    person_id,
    start_date,
    end_date,
    company,
    -- we want to get all consecutive work experiences at the same company.
    -- there is a buffer of one month in seconds (31*24*60*60)
    -- in case two experiences end and start on a separate month
    company = lag(company) over (partition by person_id order by start_date desc) and
    abs(end_date - lag(start_date) over (partition by person_id order by start_date desc)) < 31*24*60*60 as is_within_window
from work_info5
where start_date <> 0
and company is not null
```

```
(venv) [nathan@devbox /opt/dataflo/python]$ iter=1; while python -m stream.flink.test.flink_regression_test --postgres --audit --parallelism=2 --test-setting table.exec.mini-batch.enabled='false' stream/flink/test/sql/lag_gem_work_info_query5.sql; do echo iter $((iter++)); done; echo failed after $iter tries
```
will typically reproduce on the first iteration
