### ISSUE TITLE
with minibatch disabled, simple join queries on tables fail with opaque NullPointerException  

### ISSUE THREAD

**Issue by nparrish42** [fentik/flink#9]
testing 02372a4

tables foodelta and bardelta have 60-80 rows each.
if I disable minibatch and run a simple join query it fails thusly:
```
Flink SQL> SET table.exec.mini-batch.enabled='false';
[INFO] Session property has been set.

Flink SQL> select * from foodelta join bardelta using (id);
+----+-------------+-------------+-------------+-------------+-------------------------+-------------+-------------+-------------+-------------------------+
| op |          id |           a |           b |           c |            __event_time |          a0 |          b0 |          c0 |           __event_time0 |
+----+-------------+-------------+-------------+-------------+-------------------------+-------------+-------------+-------------+-------------------------+
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
```
from job manager log:
```
2022-09-09 17:28:00,710 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job collect (47e71a723e6c4c1a48b355343bec432f) switched from state FAILING to FAILED.
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:301) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:291) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:282) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:739) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:78) ~[flink-dist-1.15.0.jar:1.15.0]
        at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:443) ~[flink-dist-1.15.0.jar:1.15.0]
        at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:304) ~[flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83) ~[flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:302) ~[flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217) ~[flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78) ~[flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163) ~[flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.actor.Actor.aroundReceive(Actor.scala:537) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.actor.Actor.aroundReceive$(Actor.scala:535) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.actor.ActorCell.invoke(ActorCell.scala:548) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.dispatch.Mailbox.run(Mailbox.scala:231) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [flink-rpc-akka_f9708162-6cc3-47e7-9833-477b08081ce2.jar:1.15.0]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.NullPointerException
```

from task executor log:
```
2022-09-09 17:28:00,688 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Join[99] -> Calc[100] -> ConstraintEnforcer[101] (2/2)#0 (ec637a16a27bc05dbfd39f6dcc3b1e00) switched from RUNNING to FAILED with failure cause: java.lang.NullPointerException

2022-09-09 17:28:00,688 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Join[99] -> Calc[100] -> ConstraintEnforcer[101] (1/2)#0 (eaf40d1cdd4eb7b5ed6f7ae5339e8bd4) switched from RUNNING to FAILED with failure cause: java.lang.NullPointerException
```

the query executes fine when I enable minibatch.

dataflo branch regresstest2 python/stream/flink/test/data/pop_tables_* has the data used to construct the tables used in the above query.  

I recreated similar tables such that kafka had only inserts, the query still failed.

similar queries on smaller tables (10 rows each) producing 5 or 6 rows do not appear to be failing this way with minibatch disabled.

**Comment by sergeitsar** [comment]
@nparrish42 is therere more stacktrace here? Can we backtrack to see where the null pointer exception is coming from?
